name: root_mobile
description: "2025 Australia Global Internship Project - RooT Mobile"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.2.0
  freezed_annotation: ^3.1.0
  get: ^4.7.2
  permission_handler: ^12.0.1
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen: ^5.11.0
  freezed: ^3.2.0
  rename: ^3.1.0
  flutter_lints: ^5.0.0
  json_serializable: ^6.10.0
  build_runner: ^2.6.0
  flutter_launcher_icons: ^0.14.4
  flutter_gen_runner: ^5.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/icons/
    - assets/config/.env

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true